### ISSUE TITLE
"Log in with device" not working

### ISSUE THREAD

**Issue by vinnyperella** [bitwarden/self-host#113]
Since this feature was implemented I have not been able to get it to work with my self hosted install. When I open the browser extension and select "Log in with device" I can see the 5 word string, I then open the Bitwarden app on my phone which has "Approve login requests" enabled and select "Pending login requests" from the settings menu. I can see the request initiated from the browser extension and it has the same word string but when I click "Approve" nothing happens. The only thing I can see in the logs is from the identity container but it doesn't align with when I attempt to perform the device login.

2023-06-02 11:08:01.841 -04:00 [Error] Request to "https://push.bitwarden.com/push/register" is unsuccessful with status of BadRequest-"Bad Request"

**Comment by vinnyperella** [comment]
The login request has the following information in the Bitwarden Android app.

Device Type: Firefox Extension
IP Address: ::ffff:172.19.0.19 (container IP address rather than the actual client IP)

**Comment by MarsCandyBars** [comment]
Greetings,

At this time, _Log in with Device_ is currently only available for cloud. More information on this topic can be found here: https://bitwarden.com/help/log-in-with-device/#logging-in-with-a-device

Thanks!
