### ISSUE TITLE
beta tag on docker hub not updated

### ISSUE THREAD

**Issue by do3meli** [bitwarden/self-host#159]
It seems that the beta tag on https://hub.docker.com/r/bitwarden/self-host is not getting updated automatically by the release process. This makes pulling the latest self-host beta version a little bit more tricky than it could be.

Would it make sense to change https://github.com/bitwarden/self-host/blob/master/.github/workflows/release.yml#L282 and currently tag `beta` instead of `latest` and make a corresponding comment that after GA that should be changed to `latest`?

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I have flagged this to our engineering team.

If you wish to add any further information please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by holow29** [comment]
https://github.com/bitwarden/server/issues/3295

**Comment by do3meli** [comment]
this should be fixed in #162

**Comment by do3meli** [comment]
the `beta` tag on docker hub still does not seems to be updated. therefore i reopen this one.

**Comment by holow29** [comment]
Looks like finally fixed in #173
