### ISSUE TITLE
bitwarden / self-host recent ARM images not published on Dockerhub

### ISSUE THREAD

**Issue by joerijansen** [bitwarden/self-host#166]
Until version 2023.8.2 arm64 and arm/v7 arch images where published to the 'bitwarden/self-host:beta' tag on dockerhub. However, these tags are no longer updated on dockerhub and the version-specific tags have no support for ARM-platforms.

Could you please fix the publication of the ARM versions? A lot of users run Bitwarden on RPI's or NAS hardware with ARM processors.

**Comment by holow29** [comment]
https://github.com/bitwarden/self-host/issues/159 https://github.com/bitwarden/server/issues/3295
They said it was fixed, but I guess it was not...

**Comment by joerijansen** [comment]
Seems to be fixed with the publish of 2023.10.0-beta

**Comment by holow29** [comment]
@joerijansen Are you seeing the beta tag updated? I only see 2023.10.0-beta updated.

**Comment by joerijansen** [comment]
@holow29 the 2023.10.0-beta tag is also available for armv7 and arm64. That is good enough for me and in my opinion better than a unversioned 'beta' tag.
