### ISSUE TITLE
Discard "docker-compose" in favor of "docker compose"

### ISSUE THREAD

**Issue by sincerelysaucy** [bitwarden/self-host#222]
The published "docker-compose" binary is obsolete and unmaintained, and the "docker compose" plugin is actively being supported and built into contemporary releases of docker. Please discard the use of "docker-compose" or at least check for and use "docker compose" first in the bitwarden.sh, run.sh, and run.ps1 files. Its use encourages separately installing and relying on obsolete software, which should not be welcomed for security related software.

**Comment by Greenderella** [comment]
Hi there,

This report has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by vinnyperella** [comment]
The above issue, https://github.com/bitwarden/self-host/issues/232, is unrelated to this issue.

My instance is successfully using the 'docker compose' binary located in $HOME/.docker/cli-plugins 

```
bitwarden@bitwarden:/opt/bitwarden$ which docker-compose
bitwarden@bitwarden:/opt/bitwarden$ docker compose version
Docker Compose version v2.26.1
bitwarden@bitwarden:/opt/bitwarden$ ~/.docker/cli-plugins/docker-compose version
Docker Compose version v2.26.1
bitwarden@bitwarden:/opt/bitwarden$ ./bitwarden.sh updateself
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.3.0
Docker version 26.0.0, build 2ae903e
Docker Compose version v2.26.1 <=============== latest Docker Compose release from Github

Updated self.
bitwarden@bitwarden:/opt/bitwarden$
```
I manually update this file using the Docker Compose Github releases page https://github.com/docker/compose/releases.

I do not have the binary that comes with the apt package docker-compose-plugin in my system path so it's not being used.

```
bitwarden@bitwarden:~$ dpkg -L docker-compose-plugin
/.
/usr
/usr/libexec
/usr/libexec/docker
/usr/libexec/docker/cli-plugins
/usr/libexec/docker/cli-plugins/docker-compose
/usr/share
/usr/share/doc
/usr/share/doc/docker-compose-plugin
/usr/share/doc/docker-compose-plugin/changelog.Debian.gz
bitwarden@bitwarden:~$ /usr/libexec/docker/cli-plugins/docker-compose version
Docker Compose version v2.25.0
bitwarden@bitwarden:~$
```

**Comment by sincerelysaucy** [comment]
The #232 actually is related. If you manually install "docker-compose", the "bitwarden.sh" script is written to use it by preference. And it's obsolete and unsupported, and should no  longer even be attempted in place of the better supported "docker compose" command.

**Comment by nkadel** [comment]
Do you need a pull request for this? Because the old 'docker-compose' binary is now six months older.

**Comment by danieled-it** [comment]
Folks, for your information this just broke support for Synology NAS, where we're stuck with Synology's "[Container Manager](https://www.synology.com/en-us/dsm/feature/container-manager)" which comes with
```bash
bitwarden@DiskStation:/volume1/docker$ docker version
Client:
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.19.1
 Git commit:        876964a
 Built:             Fri Sep  8 08:19:48 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.1
  Git commit:       5fcb1cf
  Built:            Fri Sep  8 08:18:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.15
  GitCommit:        b23a389d8c181697302d163356e97dec04eb8d88
 runc:
  Version:          v1.1.4
  GitCommit:        5af893d
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00
bitwarden@DiskStation:/volume1/docker$
```
and does not like `docker compose`: 
```bash
docker: 'compose' is not a docker command.
See 'docker --help'
```

**Comment by nkadel** [comment]
Synology's version of docker is apparently obsolete. See:

      https://docs.docker.com/compose/releases/migrate/

If we still need to support 'docker-compose' for cases like yours, then the old order of operations should be reversed and 'docker composee' should be checked for first. Would you care to test that?

**Comment by nkadel** [comment]
Others have noticed the EOL docker on Synology, see:

     https://mariushosting.com/synology-docker-engine-eol/
