### ISSUE TITLE
Update with MSSQL CU12

### ISSUE THREAD

**Issue by CryptoSiD** [bitwarden/self-host#234]
Hi,

When can we expect the release with MSSQL CU12?

It's been fixed 10 days ago in https://github.com/bitwarden/server/pull/3904

**Comment by djsmith85** [comment]
The self-hosted release is always a couple of days after the cloud release. This is to ensure that any issues that might occur can be addressed before also releasing on self-hosted. The [last server release](https://github.com/bitwarden/server/releases/tag/v2024.3.0) got delayed and we did not want to release self-hosted over the weekend. 

The update you are waiting for is going to be available later today.

Closing this now.

Kind regards,
Daniel

**Comment by djsmith85** [comment]
`2024.3.0` has been released: https://github.com/bitwarden/self-host/releases/tag/v2024.3.0
