### ISSUE TITLE
bitwarden/self-host beta version 2024.3.1?

### ISSUE THREAD

**Issue by fvultee** [bitwarden/self-host#243]
Quick question.  Running bitwarden/self-host beta Docker unified on a Synology NAS.  Everything is running great, just curious about something.  When I look at the admin dashboard it says the latest server image is 2024.3.0, however under server installed it says 2024.3.1.  I can't find any reference to 2024.3.1 anywhere on the Bitwarden site or on github, any reason it would be saying I'm running a version that doesn't seem to exist?

**Comment by vinnyperella** [comment]
Self host version 2024.3.1 was released yesterday https://github.com/bitwarden/self-host/releases/tag/v2024.3.1 however the only change was updating the Key Connector to version 2024.3.1 https://github.com/bitwarden/key-connector/releases/tag/v2024.3.1. The only thing that was required was running "./bitwarden.sh updateself" if you try to run "./bitwarden.sh update" it says you are already on the latest version.

**Comment by fvultee** [comment]
Glad to see it came out, just curious that I got it 3 days before it was released.
