### ISSUE TITLE
run.sh got deleted after running ./bitwarden.sh updateself and ./bitwarden.sh update

### ISSUE THREAD

**Issue by Jabe0** [bitwarden/self-host#262]
After running ./bitwarden.sh update i get the following error message:  

> Unable to download run script from https://func.bitwarden.com/api/dl/?app=self-host&platform=linux&variant=run. Received status code: 503
> http response:
> Function host is not running.
> 

After that message the run.sh file is gone from bwdata.
Readding it and running the commands again results in the same issue.

**Comment by JasmeowTheCat** [comment]
Same here. Their function host site is down. Helpful. Luckily I noticed before stopping all the containers or I would of caused more damage.

**Comment by VoiletDragon** [comment]
Yep same problem here.

First noticed this problem when I was trying to install the latest version of Bitwarden Client App on Linux the complete vault was empty then tried to update Bitwarden to see if it fixes the problem but of course I had the same error.

```
Unable to download run script from https://func.bitwarden.com/api/dl/?app=self-host&platform=linux&variant=run. Received status code: 503
http response:
Function host is not running.
```

It seems that version 2024-5-0 & 4 is broken, I have tested 2024-1.0 and works.

Regards

**Comment by VoiletDragon** [comment]
Problem appears to be resolved now,

Regards

**Comment by Jabe0** [comment]
Even if its fixed now this should not happen when a site is down. Not on a self hosted instance.
I really hope this gets fixed in the future

**Comment by Luca180405** [comment]
I want a child from you!

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
