### ISSUE TITLE
manifest unknown: manifest unknown (the return)

### ISSUE THREAD

**Issue by FleketBreaker** [bitwarden/self-host#264]
Hi,

I have tried to update to the latest version v2024.6.0 by running the corresponding bitwarden.sh update command, when doing so, I get the following:
`manifest for bitwarden/setup:2024.6.0 not found: manifest unknown: manifest unknown`

I just checked at https://github.com/bitwarden/self-host/blob/main/bitwarden.sh and I have noticed that the script is pointing to:
`COREVERSION="2024.6.0"
WEBVERSION="2024.6.0"`

but when checking on docker hub https://hub.docker.com/r/bitwarden/setup/tags I cannot see the tag corresponding to "2024.6.0"

Any help will be very appreciated.

**Comment by ilkevinli** [comment]
I am seeing the same thing.

![Screenshot 2024-06-13 143044](https://github.com/bitwarden/self-host/assets/10118629/64556720-2834-412c-907c-ceb6ffdcbf8a)

**Comment by FleketBreaker** [comment]
> The new version is now correctly tagged on docker hub

Thank you!!
