### ISSUE TITLE
Updating: docker compose version mismatch with override file

### ISSUE THREAD

**Issue by jessicah** [bitwarden/self-host#268]
Trying to update from v2024.2.2 to latest (v2024.6.1):

```
# ./bitwarden.sh update
ERROR: Version mismatch: file /home/jessica/srv/bitwarden/bwdata/docker/docker-compose.yml specifies version 1 but extension file /home/jessica/srv/bitwarden/bwdata/docker/docker-compose.override.yml uses version 3.0
```

I worked around the issue by disabling auto-generating config file, and adding `version: '3'` to the generated `docker-compose.yml` file. Surely the compose file should specify a version...

**Comment by Krychaz** [comment]
Hello there,

Which version of Docker are you running? We require Docker version Engine 26+ - https://bitwarden.com/help/install-on-premise-linux/

**Comment by jessicah** [comment]
I have Docker version 24.0.7. Is that a new requirement? I've been running bitwarden fine for a couple years until now, with the only new issue being the lack of a version number.

**Comment by jessicah** [comment]
Ah, I see, now version is obsolete... well at least I have updated docker engine I guess! Thanks :)
