### ISSUE TITLE
In the Bitwarden browser plug-in, if you use the add, delete, or modify action, you will be logged out of the account immediately.

### ISSUE THREAD

**Issue by sanxue** [bitwarden/self-host#280]
![image](https://github.com/user-attachments/assets/f4dd357a-32e2-452a-bc74-0a0ac45c3671)
![240808_11-51-07](https://github.com/user-attachments/assets/b536775b-0745-4c6b-a8eb-2f947a63e709)

I use docker to deploy Vaultwarden, and use Bitwarden as the browser plug-in, and log in from the self-hosted address.
After the browser plug-in was updated, it has not been able to be used normally. It can only be filled, but not added, deleted, or modified.
Everything was normal before version 7.1.
In the browser plug-in, using the add, delete, or modify action will immediately and automatically log out of the account. The mobile application uses the add, delete, or modify action normally and will not automatically log out of the account.
Reinstalling the plug-in many times cannot solve the problem. After checking, the deployed Vaultwarden itself is normal. How can I solve this problem?

**Comment by sanxue** [comment]
The reason was found to be ADGUARD. It became normal after closing the plugin. The specific reason is unknown.

**Comment by BBGhub** [comment]
Hi There,

It is important to note that Vaultwarden (the new name for Bitwarden RS) is not associated with Bitwarden.

Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. The security audits granted to Bitwarden do not apply to Vaultwarden, and the Bitwarden support team cannot respond to questions regarding Vaultwarden.

Bitwarden also offers a self-hosted option, which many of our customers run in an air-gapped environment.  You can find information on this here:

https://bitwarden.com/help/install-on-premise-linux/ 

https://bitwarden.com/help/install-and-deploy-offline/
