### ISSUE TITLE
Page width not sticking

### ISSUE THREAD

**Issue by wagisdev** [bitwarden/self-host#30]
In Settings-> Options -> Enable Full Width Layout when enabled will not maintain (even though checked) in Google Chrome and MS Edge regardless of theme (dark or light) when using SSO. Checks were completed via both incognito and history/cookie purge browser sessions with fresh SSO logons.

**Comment by mimartin12** [comment]
Hey @wagisdev, please open an issue in our Clients project for this issue you are experiencing. You can find it at https://github.com/bitwarden/clients
