### ISSUE TITLE
"An error has occured" Selfhosted Server

### ISSUE THREAD

**Issue by etim808** [bitwarden/self-host#305]
When trying to connect to my self hosted lxc docker instance, I am receiving this error on iOS.

- App is updated on Docker & iOS
- Bitwarden is accessible via browser on phone w/ valid ssl cert.
- Utilizing private lan

**Comment by BBGhub** [comment]
Hi There,

Are you self-hosting using Bitwarden or Vaultwarden?

If updating does not resolve the issue at first, please try uninstalling the app, then restarting your phone, then re-installing from the App Store once more.

https://bitwarden.com/help/hosting-faqs/#q-do-bitwarden-client-apps-support-non-official-servers

**Comment by etim808** [comment]
self host Bitwarden
  
  
  
  
  
  
  

  
  
>

**Comment by BBGhub** [comment]
We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
