### ISSUE TITLE
2024.11.0, use 'docker-compose' instead of 'docker compose'

### ISSUE THREAD

**Issue by Proximus888** [bitwarden/self-host#307]
Hi, I am running Bitwarden on a Synology 718+ for a while without issues.

But I am unable to upgrade to the latest release (20214.11.0) because it errors out with ```docker: 'compose' is not a docker command.```.

Is there a way to setup Bitwarden to 'docker-compose' instead of the newer 'docker compose'. Since Synology really doesn't update there docker package often.

```
_     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.11.0
Docker version 24.0.2, build 610b8d0
docker: 'compose' is not a docker command.
See 'docker --help'
❯ docker-compose version
Docker Compose version v2.20.1-6047-g6817716
❯ docker --version
Docker version 24.0.2, build 610b8d0
```

**Comment by sammbw** [comment]
Hello, please reach out to the support team - GitHub is used for bugs and tracking issues.

Contact Bitwarden: https://bitwarden.com/contact/

Thanks!

**Comment by tykisson** [comment]
Same here, the new 2024.11.0 has broken updates. I can no longer run ./bitwarden.sh update

I would consider this a bug.

Ubuntu 22.04.5 LTS

**Comment by Proximus888** [comment]
@tykisson 

This helped me to resolve the issue. Just install ```docker compose``` as a Docker plugin. Now I am running Bitwarden 2024.11.0 on my Synology.


Run as root:
```
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
```

https://piotrkrzyzek.com/install-docker-compose-plugin-v2-on-synology-dsm-7/

**Comment by tykisson** [comment]
@Proximus888 

I looked in the script and it calls out both 'docker compose' and 'docker-compose'. 
`if command -v docker-compose &> /dev/null
then
    dccmd='docker-compose'
else
    dccmd='docker compose'
fi`

Just odd that this has suddenly broken. I've been running this for a couple years now with out issue.

I may have found the reason in [COMMIT: 8465237](https://github.com/bitwarden/self-host/commit/846523760d4425d9ef2cc5f4d174f32a8ae70ad5)

* BREAKING CHANGE: remove compat with deprecated docker-compose CLI

**Comment by Proximus888** [comment]
> * BREAKING CHANGE: remove compat with deprecated docker-compose CLI

Good find. Yes that appears to be the issue. Would be handy if they would have mentioned the 'Breaking Changes' in the changelog.

**Comment by tykisson** [comment]
FYI: I installed the package `docker-compose-v2` and now i'm able to run the update script.

Agreed this would have been good information to share. @sammbw
