### ISSUE TITLE
Docker compose VS docker-compose command

### ISSUE THREAD

**Issue by lizardkingDOTca** [bitwarden/self-host#311]
After an update to the bitwarden.sh script there was a extra version check, but it not using the docker-compose command that was validated higher up

Hence we get the following error 
docker: 'compose' is not a docker command.
https://github.com/bitwarden/self-host/blob/bf88b053c0152386df9ee6288ed2691b8c7c0bae/bitwarden.sh#L71

**Comment by SergeantConfused** [comment]
Hi @lizardkingDOTca,

Thank you for reporting this. This is related to Docker Compose V2; please check this [GitHub thread](https://github.com/bitwarden/self-host/issues/308) out for more information.

If you have any questions or concerns, please feel free to [get in touch with us](https://bitwarden.com/help/) and please include a link to this GitHub report if you do create a support ticket.

Thank you again,
