### ISSUE TITLE
Problems to update self hosted installation

### ISSUE THREAD

**Issue by acutbal** [bitwarden/self-host#312]
Hello!!
I use the self-hosted version of Bitwarden, running on a VM dedicated Ubuntu Server (22.04.5). To update, I always run ./bitwarden.sh updateself and then ./bitwarden.sh update. However, this time these commands seem to don’t work:
https://imgur.com/a/ZvtTX85

These are the versions from I’m trying to update:
https://imgur.com/a/3pc4SrQ

What I’ve done to troubleshooting:
- Reboot the VM from the Proxmox node.
- Checked whether the Sophos firewall of Pi-hole were blocking something.
- Checked open and closed issues in this Bitwarden's Github.

I’m a bit lost here. Any idea what could be happening?

Thank you very much and kind regards.

Albert.

**Comment by djsmith85** [comment]
@acutbal Possibly related to https://github.com/bitwarden/self-host/issues/308

**Comment by acutbal** [comment]
Hello, :)
I don't think so... My Bitwarden is running in Ubuntu rather than Sinology, and my docker-compose-plugin is already v2.

Regards.
