### ISSUE TITLE
Web version reported as 2022.6.1 with bitwarden.sh 2022.6.0

### ISSUE THREAD

**Issue by jecal22** [bitwarden/self-host#35]
Just upgraded bitwarden.sh to 2022.6.0.  Server is now reporting as 2022.6.2, but web is reporting as 2022.6.1 while the release info for this version indicates that web should be updated to 2022.6.2.
![bitwarden_admin_version](https://user-images.githubusercontent.com/20260386/178392200-61514ecf-8735-4ab6-9462-475a3e6b9a48.png)

**Comment by Ayitaka** [comment]
Screenshot of current self-host web portal which also shows 2022.6.1.

![self-host-showing-v2022 6 1](https://user-images.githubusercontent.com/22988712/178416632-2b989977-596e-4611-ba61-ed1765d90603.png)
