### ISSUE TITLE
Create account button doesn't work

### ISSUE THREAD

**Issue by glen4cindy** [bitwarden/self-host#72]
I'm running version 2022.12.0 of Bitwarden self-hosted on a Ubuntu 22.04 Live Server host.

I can browse my vault on my local network but when I enter all my details and click the "Create account" button, nothing happens. The screen stays on the page where I have filled all the fields.

There doesn't appear to be an update that I'm missing. I've completely removed my Ubuntu host and started from the beginning. After the new install of Bitwarden is up and running the same thing is happening.

I've tried multiple browsers.

Thanks in advance.

**Comment by chrizzlibaer** [comment]
Did you access bitwarden internally with https?
It will only accept https connections for login or creating accounts as far as I am aware.

**Comment by glen4cindy** [comment]
Actually, No. I've been working on this all evening. I thought my reverse proxy wasn't working either but it turns out it is. My domain is configured, it's forwarding to my local IP and instance of Bitwarden but only for http.

I've been able to get my SSL certificate from my domain which was issued by Let's Encrypt but I'm having a real problem getting it onto the Bitwarden instance.

I'm trying to "place your files in ./bwdata/ssl/your.domain." but I keep getting "Permission denied."

I tried to use chmod to change the permissions just long enough to copy the files and that's not allowed either it seems.

Can you help?

Thanks for your very quick reply.

**Comment by chrizzlibaer** [comment]
Bitwarden doesn't need the certificate. It's only needed that you access bitwarden by https through the reverse proxy.

The connection is then unencrypted between reverse proxy and bitwarden. But encrypted throughout the whole rest of the communication.

Bitwarden just checks if you are accessing it by https in your browser.

**Comment by glen4cindy** [comment]
I'm sorry I guess I don't understand how to make that work. I'm following the guide and it explains where to put the certificate files.

I've downloaded them from my webhost and placed them in the appropriate directory.

I did this on a completely new install of Bitwarden so everything would be fresh.

I'm not sure exactly what but something must be wrong with the certificate files because now instead of being able to lead the vault page the nginx container keeps restarting over and over. 

I'm about to give up on self hosting.

**Comment by glen4cindy** [comment]
I have an update.

I've reinstalled everything from scratch.

I'm now able to create my account and I do receive the confirmation email.

I'm still having an issue with my certificate.

Chrome is still reporting Not Secure on the vault page.

2022/12/23 00:03:20 [error] 45#45: *232 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.86.107, server: bitwarden.gl>

2022/12/23 00:03:20 [error] 45#45: OCSP_basic_verify() failed (SSL: error:27069076:OCSP routines:OCSP_basic_verify:signer certificate not found) while request>

2022/12/23 00:37:16 [error] 45#45: OCSP_basic_verify() failed (SSL: error:27069076:OCSP routines:OCSP_basic_verify:signer certificate not found) while request>

The connection also only works locally and using the IP but not the URL.

**Comment by glen4cindy** [comment]
One more update.

I can now access the secure https site by the URL: https://bitwarden.glenspcservice.com:8443/#/login

What isn't working now is the link to verify my email address.

I'm curious since I'm self hosting if I need to forward a different port?

Thanks in advance.

**Comment by glen4cindy** [comment]
This issue can be closed.

I'm able to create an account successfully.

I'm also able to browse to the https vault successfully.

Thanks for your help.

**Comment by olluz** [comment]
> This issue can be closed.
> 
> I'm able to create an account successfully.
> 
> I'm also able to browse to the https vault successfully.
> 
> Thanks for your help.

Kindly let us now how you fixed your problems as a reference....
