### ISSUE TITLE
Install and Deploy on Windows stops and does nothing

### ISSUE THREAD

**Issue by AHandless** [bitwarden/self-host#91]
### Steps To Reproduce

1. Follow the instructions provided here: [https://bitwarden.com/help/install-on-premise-windows/#install-bitwarden](https://bitwarden.com/help/install-on-premise-windows/#install-bitwarden) up to step 4.
2. Enter an instance name and database name when prompted.
3. Wait for the installation to proceed to the next step.

### Expected Result

The installation process should proceed to the next step after entering the instance name and database name.

### Actual Result

After entering the instance name and database name, the installation process hangs and does not proceed to the next step.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/7250900/231362731-518bfe40-1d64-4dfd-a95f-adec1b0193dc.png)

### Additional Context

The installation process does not proceed beyond this point, even after waiting for a long time. This issue has been encountered consistently on multiple attempts.

### Environment Details

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
Docker version 20.10.24, build 297e128

**Comment by Adedamola-Aina** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
