### ISSUE TITLE
More of a question than an issue. Why is Docker/self-host beta still 2023.02.0?

### ISSUE THREAD

**Issue by lxne** [bitwarden/self-host#94]
Hi, sorry I am quite new to docker and I don't know if updating and versioning the repository is an automated process or something done manually.

After updating my docker container with [Docker/self-host (beta)](https://hub.docker.com/r/bitwarden/self-host/tags) it is still 2023.02.0. whilst the latest GitHub version is 2023.03.01. Is it just taking some more time for the docker repository to be updated?

And I am feeling kind of stupid here: Is there a way to see the version of the bitwarden docker image over at [docker](https://hub.docker.com/r/bitwarden/self-host) before updating the container?

Best wishes,
Alex

**Comment by chrizzlibaer** [comment]
Bitwarden is intentionally holding back the newest versions a few days. They release a new version together with updating the cloud part for vault.bitwarden.com then they're testing things if everything is working good.

After the testing period the docker bitwarden-update.sh script gets the new bits and bytes.

This is also where you can see if and which version you can update to, by launching the bitwarden-update.sh

**Comment by lxne** [comment]
Thank you very much. I do understand the process now.

But feeling dumb stupid again…
> This is also where you can see if and which version you can update to, by launching the bitwarden-update.sh
Where can I launch bitwarden-update.sh ?
I don't find that file anywhere.

**Comment by chrizzlibaer** [comment]
Oh. I am very sorry! I built the bitwarden-update.sh myself.
It contains

#! /bin/bash
./bitwarden.sh update
./bitwarden.sh updateself

If you followed the install guide from 

https://bitwarden.com/help/install-on-premise-linux/

You should see the bitwarden.sh file in the folder in which you launched

`curl -Lso bitwarden.sh "https://func.bitwarden.com/api/dl/?app=self-host&platform=linux" && chmod 700 bitwarden.sh`

**Comment by joseph-flinn** [comment]
@lxne Great catch! Thanks for raising the issue.

Our release processes for the Bitwarden Unified (the `bitwarden/self-host:beta` image) in beta have not been fully finalized. The latest image looks like it was built/published right before we did the final version bump commit for the web client portion in our https://github.com/bitwarden/clients repo in the last release. The latest Unified image is fully up to date with the technical features, but missing that final commit that changes the version in the web client. We are looking into fixing this bug in the release process.

@chrizzlibaer You are also correct in that we wait a few days for our standard self-host option (the one that uses the `bitwarden.sh` scripts). Once our unified deployment option going GA, this can be the expectation of how it is released as well.

**Comment by lxne** [comment]
> If you followed the install guide from
> 
> https://bitwarden.com/help/install-on-premise-linux/

Thanks for clarification.
I see how this would help when installing in linux.
Unfortunately I am using the docker app on a synology nas. It works good. But with every image I am always not sure if there is a new version on [hub.docker.com](https://hub.docker.com). Because I cannot find any versioning there.

@joseph-flinn Thank you for providing your insights.
